version: '3.8'
services:
  frontend:
    build:
      context: apps/frontend
      dockerfile: Dockerfile
    ports:
      - 80:80
  giphy-service:
    build:
      context: apps/giphy-service
      dockerfile: Dockerfile
    env_file:
      - apps/giphy-service/.env
    ports:
      - "3000:3000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s